
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 14 2026 17:25:30 IST (Mar 14 2026 11:55:30 UTC)

// Verification Directory fv/vedic8x8 

module vedic8x8(A, B, P);
  input [7:0] A, B;
  output [15:0] P;
  wire [7:0] A, B;
  wire [15:0] P;
  wire [15:0] pp1;
  wire [15:0] pp7;
  wire [15:0] pp0;
  wire [15:0] pp5;
  wire [15:0] pp2;
  wire [15:0] pp3;
  wire [15:0] pp6;
  wire [15:0] pp4;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6,
       WALLACE_CSA_DUMMY_OP_groupi_n_7, WALLACE_CSA_DUMMY_OP_groupi_n_8;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15,
       WALLACE_CSA_DUMMY_OP_groupi_n_16;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23,
       WALLACE_CSA_DUMMY_OP_groupi_n_24;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31,
       WALLACE_CSA_DUMMY_OP_groupi_n_32;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_41,
       WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_49;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_50,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55,
       WALLACE_CSA_DUMMY_OP_groupi_n_56,
       WALLACE_CSA_DUMMY_OP_groupi_n_57;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_58,
       WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63,
       WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_65;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_67,
       WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_69,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71,
       WALLACE_CSA_DUMMY_OP_groupi_n_72,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_75,
       WALLACE_CSA_DUMMY_OP_groupi_n_77,
       WALLACE_CSA_DUMMY_OP_groupi_n_78,
       WALLACE_CSA_DUMMY_OP_groupi_n_79,
       WALLACE_CSA_DUMMY_OP_groupi_n_80,
       WALLACE_CSA_DUMMY_OP_groupi_n_81,
       WALLACE_CSA_DUMMY_OP_groupi_n_82,
       WALLACE_CSA_DUMMY_OP_groupi_n_83;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_84,
       WALLACE_CSA_DUMMY_OP_groupi_n_85,
       WALLACE_CSA_DUMMY_OP_groupi_n_86,
       WALLACE_CSA_DUMMY_OP_groupi_n_87,
       WALLACE_CSA_DUMMY_OP_groupi_n_88,
       WALLACE_CSA_DUMMY_OP_groupi_n_89,
       WALLACE_CSA_DUMMY_OP_groupi_n_91,
       WALLACE_CSA_DUMMY_OP_groupi_n_92;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_93,
       WALLACE_CSA_DUMMY_OP_groupi_n_95,
       WALLACE_CSA_DUMMY_OP_groupi_n_96,
       WALLACE_CSA_DUMMY_OP_groupi_n_97,
       WALLACE_CSA_DUMMY_OP_groupi_n_99,
       WALLACE_CSA_DUMMY_OP_groupi_n_101,
       WALLACE_CSA_DUMMY_OP_groupi_n_103,
       WALLACE_CSA_DUMMY_OP_groupi_n_105;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_107,
       WALLACE_CSA_DUMMY_OP_groupi_n_109;
  AND2X1 g663__2398(.A (B[6]), .B (A[1]), .Y (pp1[7]));
  AND2X1 g664__5107(.A (B[7]), .B (A[7]), .Y (pp7[14]));
  AND2X1 g665__6260(.A (B[5]), .B (A[7]), .Y (pp7[12]));
  AND2X1 g666__4319(.A (B[2]), .B (A[0]), .Y (pp0[2]));
  AND2X1 g667__8428(.A (B[1]), .B (A[7]), .Y (pp7[8]));
  AND2X1 g668__5526(.A (B[4]), .B (A[0]), .Y (pp0[4]));
  AND2X1 g669__6783(.A (B[5]), .B (A[5]), .Y (pp5[10]));
  AND2X1 g670__3680(.A (B[6]), .B (A[0]), .Y (pp0[6]));
  AND2X1 g671__1617(.A (B[7]), .B (A[0]), .Y (pp0[7]));
  AND2X1 g672__2802(.A (B[0]), .B (A[1]), .Y (pp1[1]));
  AND2X1 g673__1705(.A (B[0]), .B (A[2]), .Y (pp2[2]));
  AND2X1 g674__5122(.A (B[2]), .B (A[1]), .Y (pp1[3]));
  AND2X1 g675__8246(.A (B[3]), .B (A[1]), .Y (pp1[4]));
  AND2X1 g676__7098(.A (B[4]), .B (A[1]), .Y (pp1[5]));
  AND2X1 g677__6131(.A (B[7]), .B (A[1]), .Y (pp1[8]));
  AND2X1 g678__1881(.A (B[4]), .B (A[5]), .Y (pp5[9]));
  AND2X2 g679__5115(.A (B[0]), .B (A[0]), .Y (P[0]));
  AND2X1 g680__7482(.A (B[3]), .B (A[5]), .Y (pp5[8]));
  AND2X1 g681__4733(.A (B[5]), .B (A[1]), .Y (pp1[6]));
  AND2X1 g682__6161(.A (B[1]), .B (A[2]), .Y (pp2[3]));
  AND2X1 g683__9315(.A (B[2]), .B (A[5]), .Y (pp5[7]));
  AND2X1 g684__9945(.A (B[3]), .B (A[2]), .Y (pp2[5]));
  AND2X1 g685__2883(.A (B[0]), .B (A[7]), .Y (pp7[7]));
  AND2X1 g686__2346(.A (B[5]), .B (A[2]), .Y (pp2[7]));
  AND2X1 g687__1666(.A (B[6]), .B (A[2]), .Y (pp2[8]));
  AND2X1 g688__7410(.A (B[1]), .B (A[5]), .Y (pp5[6]));
  AND2X1 g689__6417(.A (B[1]), .B (A[1]), .Y (pp1[2]));
  AND2X1 g690__5477(.A (B[0]), .B (A[3]), .Y (pp3[3]));
  AND2X1 g691__2398(.A (B[1]), .B (A[3]), .Y (pp3[4]));
  AND2X1 g692__5107(.A (B[2]), .B (A[3]), .Y (pp3[5]));
  AND2X1 g693__6260(.A (B[0]), .B (A[5]), .Y (pp5[5]));
  AND2X1 g694__4319(.A (B[4]), .B (A[3]), .Y (pp3[7]));
  AND2X1 g695__8428(.A (B[5]), .B (A[6]), .Y (pp6[11]));
  AND2X1 g696__5526(.A (B[7]), .B (A[4]), .Y (pp4[11]));
  AND2X1 g697__6783(.A (B[5]), .B (A[0]), .Y (pp0[5]));
  AND2X1 g698__3680(.A (B[7]), .B (A[3]), .Y (pp3[10]));
  AND2X1 g699__1617(.A (B[0]), .B (A[4]), .Y (pp4[4]));
  AND2X1 g700__2802(.A (B[1]), .B (A[4]), .Y (pp4[5]));
  AND2X1 g701__1705(.A (B[3]), .B (A[0]), .Y (pp0[3]));
  AND2X1 g702__5122(.A (B[3]), .B (A[4]), .Y (pp4[7]));
  AND2X1 g703__8246(.A (B[4]), .B (A[7]), .Y (pp7[11]));
  AND2X1 g704__7098(.A (B[7]), .B (A[6]), .Y (pp6[13]));
  AND2X1 g705__6131(.A (B[6]), .B (A[4]), .Y (pp4[10]));
  AND2X1 g706__1881(.A (B[1]), .B (A[0]), .Y (pp0[1]));
  AND2X1 g707__5115(.A (B[5]), .B (A[4]), .Y (pp4[9]));
  AND2X1 g708__7482(.A (B[4]), .B (A[4]), .Y (pp4[8]));
  AND2X1 g709__4733(.A (B[6]), .B (A[6]), .Y (pp6[12]));
  AND2X1 g710__6161(.A (B[2]), .B (A[4]), .Y (pp4[6]));
  AND2X1 g711__9315(.A (B[5]), .B (A[3]), .Y (pp3[8]));
  AND2X1 g712__9945(.A (B[6]), .B (A[7]), .Y (pp7[13]));
  AND2X1 g713__2883(.A (B[3]), .B (A[7]), .Y (pp7[10]));
  AND2X1 g714__2346(.A (B[2]), .B (A[2]), .Y (pp2[4]));
  AND2X1 g715__1666(.A (B[4]), .B (A[2]), .Y (pp2[6]));
  AND2X1 g716__7410(.A (B[7]), .B (A[5]), .Y (pp5[12]));
  AND2X1 g717__6417(.A (B[7]), .B (A[2]), .Y (pp2[9]));
  AND2X1 g718__5477(.A (B[1]), .B (A[6]), .Y (pp6[7]));
  AND2X1 g719__2398(.A (B[3]), .B (A[3]), .Y (pp3[6]));
  AND2X1 g720__5107(.A (B[4]), .B (A[6]), .Y (pp6[10]));
  AND2X1 g721__6260(.A (B[6]), .B (A[3]), .Y (pp3[9]));
  AND2X1 g722__4319(.A (B[3]), .B (A[6]), .Y (pp6[9]));
  AND2X1 g723__8428(.A (B[2]), .B (A[6]), .Y (pp6[8]));
  AND2X1 g724__5526(.A (B[2]), .B (A[7]), .Y (pp7[9]));
  AND2X1 g725__6783(.A (B[0]), .B (A[6]), .Y (pp6[6]));
  AND2X1 g726__3680(.A (B[6]), .B (A[5]), .Y (pp5[11]));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3741__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .B (pp7[14]), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_109), .CO (P[15]), .S (P[14]));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3742__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_107), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_109), .S (P[13]));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3743__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_105), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_107), .S (P[12]));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3744__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_91), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_103), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_105), .S (P[11]));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3745__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_95), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_101), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_103), .S (P[10]));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3746__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_96), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_99), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_101), .S (P[9]));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3747__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_99), .S (P[8]));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3748__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_81), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .S (P[7]));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3749__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_95), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_96));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3750__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_89), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .S (P[6]));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3751__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_91), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_92));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3752__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_89), .S (P[5]));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3753__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_88));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3754__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_86));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3755__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_84));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3756__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_81), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_82));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3757__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_80));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3758__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_78));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3759__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .S (P[4]));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3760__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_74));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3761__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_72));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3762__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_70));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3763__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_68));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3764__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .S (P[3]));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3765__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_64));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3766__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_62));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3767__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .B (pp4[11]), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3768__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_58));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3769__1617(.A (pp4[10]), .B
       (pp5[10]), .CI (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_56));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3770__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_54));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3771__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3772__5122(.A (pp6[13]), .B
       (pp7[13]), .CI (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  ADDFX2 WALLACE_CSA_DUMMY_OP_groupi_g3773__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .B (pp0[2]), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .S (P[2]));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3774__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .B (pp4[5]), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3775__6131(.A (pp4[7]), .B
       (pp5[7]), .CI (pp2[7]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_43),
       .S (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3776__1881(.A (pp6[10]), .B
       (pp7[10]), .CI (pp3[10]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3777__5115(.A (pp0[3]), .B
       (pp2[3]), .CI (WALLACE_CSA_DUMMY_OP_groupi_n_10), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3778__7482(.A (pp6[9]), .B
       (pp7[9]), .CI (pp3[9]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_37),
       .S (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3779__4733(.A (pp6[12]), .B
       (pp7[12]), .CI (pp5[12]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3780__6161(.A (pp0[6]), .B
       (pp2[6]), .CI (WALLACE_CSA_DUMMY_OP_groupi_n_13), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3781__9315(.A (pp6[11]), .B
       (pp7[11]), .CI (pp5[11]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3782__9945(.A (pp1[8]), .B
       (pp2[8]), .CI (WALLACE_CSA_DUMMY_OP_groupi_n_6), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3783__2883(.A (pp4[9]), .B
       (pp5[9]), .CI (pp2[9]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_27),
       .S (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3784__2346(.A (pp2[4]), .B
       (pp3[4]), .CI (pp0[4]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_25),
       .S (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3785__1666(.A (pp4[6]), .B
       (pp5[6]), .CI (pp3[6]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_23),
       .S (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3786__7410(.A (pp4[8]), .B
       (pp5[8]), .CI (pp3[8]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_21),
       .S (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3787__6417(.A (pp2[5]), .B
       (pp3[5]), .CI (pp0[5]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_19),
       .S (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3788__5477(.A (pp0[7]), .B
       (pp3[7]), .CI (pp1[7]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_17),
       .S (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3789__2398(.A (pp7[7]), .B
       (pp6[7]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_15), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3790__5107(.A (pp5[5]), .B
       (pp1[5]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_13), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  ADDHX1 WALLACE_CSA_DUMMY_OP_groupi_g3791__6260(.A (pp0[1]), .B
       (pp1[1]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_11), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3792__4319(.A (pp3[3]), .B
       (pp1[3]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_9), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3793__8428(.A (pp6[6]), .B
       (pp1[6]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_7), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3794__5526(.A (pp7[8]), .B
       (pp6[8]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_5), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3795__6783(.A (pp2[2]), .B
       (pp1[2]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_3), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3796__3680(.A (pp4[4]), .B
       (pp1[4]), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_1), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  BUFX2 WALLACE_CSA_DUMMY_OP_groupi_drc_bufs(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .Y (P[1]));
endmodule

